// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brain-variants/HolographicCortex.tsx": () => import("../components/mockups/brain-variants/HolographicCortex.tsx"),
  "./components/mockups/brain-variants/NeuralCosmos.tsx": () => import("../components/mockups/brain-variants/NeuralCosmos.tsx"),
  "./components/mockups/brain-variants/QuantumLattice.tsx": () => import("../components/mockups/brain-variants/QuantumLattice.tsx")
};
