/**
 * Task Graph View — Features 1 (Real Planning Agent), 2 (Parallel Scheduler), 7 (Multi-Agent Comms).
 *
 * Shows the full dependency graph generated by MARK's planner.
 * Uses React Flow nodes arranged by dependency level.
 * Agent messages feed shown below the graph.
 */
import React, { useEffect, useState, useCallback } from 'react';
import {
  ReactFlow, Node, Edge, Background, Controls, MiniMap,
  useNodesState, useEdgesState, MarkerType,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { cn } from '@/lib/utils';
import { useMarkStore } from '@/store/markStore';
import {
  GitBranch, RefreshCw, MessageSquare, ChevronDown, ChevronRight,
  Play, CheckCircle, XCircle, Loader2, Pause, Clock,
} from 'lucide-react';

interface TaskNode {
  id:           string;
  title:        string;
  description:  string;
  dependencies: string[];
  complexity:   'low' | 'medium' | 'high';
  status:       'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'blocked';
  worker:       string;
  result:       string;
}

interface AgentMsg {
  id:         string;
  sender:     string;
  receiver:   string;
  timestamp:  string;
  task:       string;
  payload:    Record<string, unknown>;
  confidence: number;
}

const STATUS_COLORS: Record<string, { bg: string; border: string; text: string }> = {
  pending:   { bg: 'hsl(var(--muted) / 0.4)', border: 'hsl(var(--border))',       text: 'hsl(var(--muted-foreground))' },
  running:   { bg: 'hsl(264 100% 60% / 0.2)', border: 'hsl(264 100% 60%)',        text: 'hsl(264 100% 75%)' },
  completed: { bg: 'hsl(142 70% 30% / 0.2)',  border: 'hsl(142 70% 50%)',         text: 'hsl(142 70% 65%)' },
  failed:    { bg: 'hsl(0 72% 30% / 0.2)',    border: 'hsl(0 72% 50%)',           text: 'hsl(0 72% 65%)' },
  cancelled: { bg: 'hsl(var(--muted) / 0.2)', border: 'hsl(var(--muted-foreground)/0.4)', text: 'hsl(var(--muted-foreground))' },
  blocked:   { bg: 'hsl(30 70% 30% / 0.2)',   border: 'hsl(30 70% 50%)',          text: 'hsl(30 70% 65%)' },
};

const COMPLEXITY_DOT: Record<string, string> = { low: 'bg-emerald-400', medium: 'bg-amber-400', high: 'bg-red-400' };

const STATUS_ICON: Record<string, React.ReactElement> = {
  pending:   <Clock     className="w-3 h-3" />,
  running:   <Loader2   className="w-3 h-3 animate-spin" />,
  completed: <CheckCircle className="w-3 h-3" />,
  failed:    <XCircle   className="w-3 h-3" />,
  cancelled: <XCircle   className="w-3 h-3" />,
  blocked:   <Pause     className="w-3 h-3" />,
};

function buildFlowNodes(tasks: TaskNode[]): { nodes: Node[]; edges: Edge[] } {
  // Topological layering
  const layers: string[][] = [];
  const placed = new Set<string>();

  const layer0 = tasks.filter(t => t.dependencies.length === 0).map(t => t.id);
  if (layer0.length) { layers.push(layer0); layer0.forEach(id => placed.add(id)); }

  let safety = 0;
  while (placed.size < tasks.length && safety++ < 20) {
    const next = tasks.filter(t => !placed.has(t.id) && t.dependencies.every(d => placed.has(d))).map(t => t.id);
    if (!next.length) break;
    layers.push(next);
    next.forEach(id => placed.add(id));
  }
  // Leftover
  const leftover = tasks.filter(t => !placed.has(t.id)).map(t => t.id);
  if (leftover.length) layers.push(leftover);

  const nodes: Node[] = [];
  const edges: Edge[] = [];

  layers.forEach((layer, li) => {
    layer.forEach((id, ni) => {
      const task   = tasks.find(t => t.id === id)!;
      const colors = STATUS_COLORS[task.status] || STATUS_COLORS.pending;
      nodes.push({
        id,
        position: { x: li * 200, y: ni * 100 - (layer.length - 1) * 50 },
        data: { label: task.title, task },
        style: {
          background: colors.bg,
          border:     `1px solid ${colors.border}`,
          borderRadius: 8,
          padding: '6px 10px',
          fontSize: 11,
          color:   colors.text,
          minWidth: 120,
          boxShadow: task.status === 'running' ? `0 0 8px ${colors.border}` : 'none',
        },
      });
    });
  });

  tasks.forEach(task => {
    task.dependencies.forEach(dep => {
      edges.push({
        id:         `${dep}->${task.id}`,
        source:     dep,
        target:     task.id,
        animated:   task.status === 'running',
        markerEnd:  { type: MarkerType.ArrowClosed },
        style:      { stroke: 'hsl(var(--border))' },
      });
    });
  });

  return { nodes, edges };
}

export function TaskGraphView() {
  const { serverUrl } = useMarkStore();
  const [tasks,    setTasks]   = useState<TaskNode[]>([]);
  const [messages, setMessages] = useState<AgentMsg[]>([]);
  const [loading,  setLoading] = useState(false);
  const [tab,      setTab]     = useState<'graph' | 'messages'>('graph');
  const [showMsg,  setShowMsg] = useState<string | null>(null);
  const [nodes, setNodes, onNodesChange] = useNodesState<Node>([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([]);

  const load = async () => {
    setLoading(true);
    try {
      const [g, m] = await Promise.all([
        fetch(`${serverUrl}/task-graph`).then(r => r.json()),
        fetch(`${serverUrl}/agent/messages?limit=100`).then(r => r.json()),
      ]);
      const loadedTasks: TaskNode[] = g.nodes || [];
      setTasks(loadedTasks);
      const { nodes: n, edges: e } = buildFlowNodes(loadedTasks);
      setNodes(n);
      setEdges(e);
      setMessages(m.messages || []);
    } catch { /* offline */ }
    setLoading(false);
  };

  useEffect(() => { load(); }, [serverUrl]);
  useEffect(() => {
    const id = setInterval(load, 4000);
    return () => clearInterval(id);
  }, [serverUrl]);

  return (
    <div className="flex flex-col h-full text-sm">
      <div className="flex items-center justify-between px-4 py-2.5 border-b border-border/50 shrink-0">
        <div className="flex items-center gap-2">
          <GitBranch className="w-4 h-4 text-accent" />
          <span className="font-semibold">Task Graph</span>
          {tasks.length > 0 && (
            <span className="text-xs text-muted-foreground">({tasks.length} tasks)</span>
          )}
        </div>
        <button onClick={load} className="p-1 hover:bg-muted/40 rounded">
          <RefreshCw className={cn('w-3.5 h-3.5', loading && 'animate-spin')} />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-border/40 shrink-0">
        {(['graph', 'messages'] as const).map(t => (
          <button key={t} onClick={() => setTab(t)}
            className={cn(
              'px-4 py-2 text-xs font-medium transition-colors capitalize',
              tab === t ? 'border-b-2 border-accent text-accent' : 'text-muted-foreground hover:text-foreground',
            )}
          >
            {t === 'messages' ? (
              <><MessageSquare className="w-3 h-3 inline mr-1" />Agent Messages ({messages.length})</>
            ) : t}
          </button>
        ))}
      </div>

      {tab === 'graph' && (
        <div className="flex flex-1 overflow-hidden">
          {/* Flow canvas */}
          <div className="flex-1">
            {tasks.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-full text-muted-foreground">
                <GitBranch className="w-10 h-10 mb-2 opacity-20" />
                <p className="text-xs text-center">
                  Ask Elena to start a task<br/>to see the dependency graph
                </p>
              </div>
            ) : (
              <ReactFlow
                nodes={nodes} edges={edges}
                onNodesChange={onNodesChange}
                onEdgesChange={onEdgesChange}
                fitView
              >
                <Background color="hsl(var(--border))" gap={16} />
                <Controls />
                <MiniMap
                  nodeColor={(n) => {
                    const task = tasks.find(t => t.id === n.id);
                    return STATUS_COLORS[task?.status || 'pending']?.border || 'hsl(var(--border))';
                  }}
                />
              </ReactFlow>
            )}
          </div>

          {/* Task list sidebar */}
          {tasks.length > 0 && (
            <div className="w-52 border-l border-border/50 overflow-y-auto shrink-0">
              {tasks.map(task => {
                const colors = STATUS_COLORS[task.status] || STATUS_COLORS.pending;
                return (
                  <div key={task.id} className="px-3 py-2 border-b border-border/20 hover:bg-muted/10">
                    <div className="flex items-center gap-1.5">
                      <span style={{ color: colors.text }}>{STATUS_ICON[task.status]}</span>
                      <span className="text-xs font-medium truncate">{task.title}</span>
                      <span className={cn('w-1.5 h-1.5 rounded-full ml-auto shrink-0', COMPLEXITY_DOT[task.complexity])} />
                    </div>
                    <p className="text-[10px] text-muted-foreground mt-0.5 truncate">{task.worker}</p>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}

      {tab === 'messages' && (
        <div className="flex-1 overflow-y-auto">
          {messages.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-40 text-muted-foreground">
              <MessageSquare className="w-8 h-8 mb-2 opacity-30" />
              <p className="text-xs">No inter-agent messages yet</p>
            </div>
          ) : (
            <div className="space-y-0">
              {messages.map(msg => (
                <div key={msg.id} className="px-4 py-2.5 border-b border-border/20 hover:bg-muted/10">
                  <div className="flex items-baseline justify-between">
                    <div className="text-xs">
                      <span className="text-accent font-medium">{msg.sender}</span>
                      <span className="text-muted-foreground mx-1">→</span>
                      <span className="font-medium">{msg.receiver}</span>
                    </div>
                    <span className="text-[10px] text-muted-foreground">{msg.timestamp.slice(11, 19)}</span>
                  </div>
                  <p className="text-xs text-muted-foreground mt-0.5 truncate">{msg.task}</p>
                  <div className="flex items-center gap-1 mt-0.5">
                    <div className="h-1 bg-muted/30 rounded-full flex-1 overflow-hidden">
                      <div className="h-full bg-accent/50 rounded-full" style={{ width: `${msg.confidence * 100}%` }} />
                    </div>
                    <span className="text-[10px] text-muted-foreground">{Math.round(msg.confidence * 100)}%</span>
                  </div>
                  {showMsg === msg.id ? (
                    <pre className="text-[10px] font-mono mt-1 text-muted-foreground whitespace-pre-wrap">
                      {JSON.stringify(msg.payload, null, 2)}
                    </pre>
                  ) : Object.keys(msg.payload).length > 0 && (
                    <button onClick={() => setShowMsg(msg.id)} className="text-[10px] text-accent/70 hover:text-accent mt-0.5">
                      Show payload ▾
                    </button>
                  )}
                  {showMsg === msg.id && (
                    <button onClick={() => setShowMsg(null)} className="text-[10px] text-accent/70 hover:text-accent mt-0.5">
                      Hide ▴
                    </button>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
